// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABgeTqe3MCcIaSi59OEAyi3cXSpXsGYH4',
    appId: '1:988921595413:web:7f1774b7be82d0e1cdb01c',
    messagingSenderId: '988921595413',
    projectId: 'bdmobile-35e13',
    authDomain: 'bdmobile-35e13.firebaseapp.com',
    storageBucket: 'bdmobile-35e13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzxtLCq5gc2R2TNLicodmcVYxkfcSRHVo',
    appId: '1:988921595413:android:0ababb4d166e5c0acdb01c',
    messagingSenderId: '988921595413',
    projectId: 'bdmobile-35e13',
    storageBucket: 'bdmobile-35e13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChsFwEcI_fxns_Lbc8gKNFOpKG1IANCiU',
    appId: '1:988921595413:ios:2ff09338fb85dc7ccdb01c',
    messagingSenderId: '988921595413',
    projectId: 'bdmobile-35e13',
    storageBucket: 'bdmobile-35e13.appspot.com',
    iosBundleId: 'com.example.projetmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChsFwEcI_fxns_Lbc8gKNFOpKG1IANCiU',
    appId: '1:988921595413:ios:2ff09338fb85dc7ccdb01c',
    messagingSenderId: '988921595413',
    projectId: 'bdmobile-35e13',
    storageBucket: 'bdmobile-35e13.appspot.com',
    iosBundleId: 'com.example.projetmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABgeTqe3MCcIaSi59OEAyi3cXSpXsGYH4',
    appId: '1:988921595413:web:8991f94d53ad4219cdb01c',
    messagingSenderId: '988921595413',
    projectId: 'bdmobile-35e13',
    authDomain: 'bdmobile-35e13.firebaseapp.com',
    storageBucket: 'bdmobile-35e13.appspot.com',
  );
}
